//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player Gameplay"",
            ""id"": ""ffe028ad-f917-4048-b57c-edd31b8401fb"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8648a068-8fc3-4186-b7ae-8c7fa96fd415"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5049b5d6-dc12-4319-98e0-8ae5cc4ff627"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockOn"",
                    ""type"": ""Button"",
                    ""id"": ""dda6150b-be18-4e9b-9071-d785bd86bb8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EastButton"",
                    ""type"": ""Button"",
                    ""id"": ""641ae0d4-30ea-4823-a9d3-912e4ae35e2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SouthButton"",
                    ""type"": ""Button"",
                    ""id"": ""cd7d344c-0c3f-448b-8dee-c006c8667ba6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NorthButton"",
                    ""type"": ""Button"",
                    ""id"": ""84c35349-b327-48d7-803d-a1834d8abd02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftLightButton"",
                    ""type"": ""Button"",
                    ""id"": ""9ba54142-917a-4979-ad0d-5337b71251f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHeavyButton"",
                    ""type"": ""Button"",
                    ""id"": ""760b26cf-2edc-4143-b19e-7feaa85c42ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightLightButton"",
                    ""type"": ""Button"",
                    ""id"": ""f4c30eb7-e7cc-43e1-8e37-072ac2e97a81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHeavyButton"",
                    ""type"": ""Button"",
                    ""id"": ""3414671a-3eab-49d2-84ba-b1ee8e739c08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPad-Up"",
                    ""type"": ""Button"",
                    ""id"": ""edaa4c18-ba27-4fb7-9318-f9275b02f9d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPad-Down"",
                    ""type"": ""Button"",
                    ""id"": ""be6f722f-b0ac-4694-b4a7-5322cd8544d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPad-Left"",
                    ""type"": ""Button"",
                    ""id"": ""c5c79979-2108-417e-aabe-79df5976228d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPad-Right"",
                    ""type"": ""Button"",
                    ""id"": ""e0ce5b39-72f5-4c3b-ac57-5d5e88f4e046"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""79ab54b0-685f-4083-8e3b-4859ff9cfc24"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""79de2aa7-f25f-41c5-9deb-e09b2109e53f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""edcb32ca-a572-4d19-b721-a337aca3ebf3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1ed87c68-4de2-4b46-b9da-44ec3b1bec0b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bf1b8193-b315-4490-9841-20cf0f0113a7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4235fa45-fc4f-42d2-8645-a95a8aa7c5d5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea7c2a78-14cd-43e8-940a-de05c251f997"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25e1dc45-2871-4118-98e0-023c0571adb3"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61a72952-e7f1-4b48-81f8-fa93eafdf0ad"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""EastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c8c9913-2193-4932-83fc-74c6165289c5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""EastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a7ebb87-479e-4b69-aa63-51b0d7cf641b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LeftLightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8b4befa-e368-4ee8-83bd-37900324fb8b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftLightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c699254-4271-4814-b6c7-1dd0d4e6851d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LeftHeavyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96e743ae-471e-47b4-913e-887248a7e66e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftHeavyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41a2948f-8d7a-4ccb-b63b-da14fe41cc9b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RightLightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""364367d2-cb7b-4b9f-9fda-5c1837411ee5"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightLightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99ac181c-5051-4bc1-99f0-5798bb6dad95"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RightHeavyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02404cb6-7eb5-4832-af26-64564c749d5a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightHeavyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2304b7a-f407-4bb3-ae3f-cf70779bbbcf"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SouthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf303936-aa99-415e-8ce3-029ef0082185"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SouthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87092cf6-eea8-4a17-91a6-8868cad25543"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DPad-Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""473edd4b-efa0-4258-9ea1-9cbd5a5b0f41"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPad-Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62c88e84-b920-4b6e-9b51-9db4b073646c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DPad-Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77b12d54-b3d4-4e59-90bc-37af28d271c1"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPad-Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa67dd95-79ba-4423-831d-d9de82847965"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DPad-Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfa8cad1-3e5a-4664-b7ee-8da18169537b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPad-Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bc4cfce-c3d7-43bb-8971-6448c3995a78"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DPad-Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""401369c4-708b-4f9f-9a7e-8a4ca34000dc"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPad-Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a8d9af3-147f-48f5-99a0-69aa10a79cf7"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LockOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16c473c3-f105-4005-a4d5-cc54c5e35dd3"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LockOn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0a702da-33c3-40a6-93ce-4876dff85970"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""NorthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0b82afa-3866-4c29-ac18-f0d6b3004625"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NorthButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player Gameplay
        m_PlayerGameplay = asset.FindActionMap("Player Gameplay", throwIfNotFound: true);
        m_PlayerGameplay_Movement = m_PlayerGameplay.FindAction("Movement", throwIfNotFound: true);
        m_PlayerGameplay_CameraMovement = m_PlayerGameplay.FindAction("CameraMovement", throwIfNotFound: true);
        m_PlayerGameplay_LockOn = m_PlayerGameplay.FindAction("LockOn", throwIfNotFound: true);
        m_PlayerGameplay_EastButton = m_PlayerGameplay.FindAction("EastButton", throwIfNotFound: true);
        m_PlayerGameplay_SouthButton = m_PlayerGameplay.FindAction("SouthButton", throwIfNotFound: true);
        m_PlayerGameplay_NorthButton = m_PlayerGameplay.FindAction("NorthButton", throwIfNotFound: true);
        m_PlayerGameplay_LeftLightButton = m_PlayerGameplay.FindAction("LeftLightButton", throwIfNotFound: true);
        m_PlayerGameplay_LeftHeavyButton = m_PlayerGameplay.FindAction("LeftHeavyButton", throwIfNotFound: true);
        m_PlayerGameplay_RightLightButton = m_PlayerGameplay.FindAction("RightLightButton", throwIfNotFound: true);
        m_PlayerGameplay_RightHeavyButton = m_PlayerGameplay.FindAction("RightHeavyButton", throwIfNotFound: true);
        m_PlayerGameplay_DPadUp = m_PlayerGameplay.FindAction("DPad-Up", throwIfNotFound: true);
        m_PlayerGameplay_DPadDown = m_PlayerGameplay.FindAction("DPad-Down", throwIfNotFound: true);
        m_PlayerGameplay_DPadLeft = m_PlayerGameplay.FindAction("DPad-Left", throwIfNotFound: true);
        m_PlayerGameplay_DPadRight = m_PlayerGameplay.FindAction("DPad-Right", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player Gameplay
    private readonly InputActionMap m_PlayerGameplay;
    private IPlayerGameplayActions m_PlayerGameplayActionsCallbackInterface;
    private readonly InputAction m_PlayerGameplay_Movement;
    private readonly InputAction m_PlayerGameplay_CameraMovement;
    private readonly InputAction m_PlayerGameplay_LockOn;
    private readonly InputAction m_PlayerGameplay_EastButton;
    private readonly InputAction m_PlayerGameplay_SouthButton;
    private readonly InputAction m_PlayerGameplay_NorthButton;
    private readonly InputAction m_PlayerGameplay_LeftLightButton;
    private readonly InputAction m_PlayerGameplay_LeftHeavyButton;
    private readonly InputAction m_PlayerGameplay_RightLightButton;
    private readonly InputAction m_PlayerGameplay_RightHeavyButton;
    private readonly InputAction m_PlayerGameplay_DPadUp;
    private readonly InputAction m_PlayerGameplay_DPadDown;
    private readonly InputAction m_PlayerGameplay_DPadLeft;
    private readonly InputAction m_PlayerGameplay_DPadRight;
    public struct PlayerGameplayActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerGameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerGameplay_Movement;
        public InputAction @CameraMovement => m_Wrapper.m_PlayerGameplay_CameraMovement;
        public InputAction @LockOn => m_Wrapper.m_PlayerGameplay_LockOn;
        public InputAction @EastButton => m_Wrapper.m_PlayerGameplay_EastButton;
        public InputAction @SouthButton => m_Wrapper.m_PlayerGameplay_SouthButton;
        public InputAction @NorthButton => m_Wrapper.m_PlayerGameplay_NorthButton;
        public InputAction @LeftLightButton => m_Wrapper.m_PlayerGameplay_LeftLightButton;
        public InputAction @LeftHeavyButton => m_Wrapper.m_PlayerGameplay_LeftHeavyButton;
        public InputAction @RightLightButton => m_Wrapper.m_PlayerGameplay_RightLightButton;
        public InputAction @RightHeavyButton => m_Wrapper.m_PlayerGameplay_RightHeavyButton;
        public InputAction @DPadUp => m_Wrapper.m_PlayerGameplay_DPadUp;
        public InputAction @DPadDown => m_Wrapper.m_PlayerGameplay_DPadDown;
        public InputAction @DPadLeft => m_Wrapper.m_PlayerGameplay_DPadLeft;
        public InputAction @DPadRight => m_Wrapper.m_PlayerGameplay_DPadRight;
        public InputActionMap Get() { return m_Wrapper.m_PlayerGameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerGameplayActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerGameplayActions instance)
        {
            if (m_Wrapper.m_PlayerGameplayActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnMovement;
                @CameraMovement.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnCameraMovement;
                @CameraMovement.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnCameraMovement;
                @CameraMovement.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnCameraMovement;
                @LockOn.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLockOn;
                @LockOn.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLockOn;
                @LockOn.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLockOn;
                @EastButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnEastButton;
                @EastButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnEastButton;
                @EastButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnEastButton;
                @SouthButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnSouthButton;
                @SouthButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnSouthButton;
                @SouthButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnSouthButton;
                @NorthButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnNorthButton;
                @NorthButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnNorthButton;
                @NorthButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnNorthButton;
                @LeftLightButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftLightButton;
                @LeftLightButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftLightButton;
                @LeftLightButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftLightButton;
                @LeftHeavyButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftHeavyButton;
                @LeftHeavyButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftHeavyButton;
                @LeftHeavyButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftHeavyButton;
                @RightLightButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightLightButton;
                @RightLightButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightLightButton;
                @RightLightButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightLightButton;
                @RightHeavyButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightHeavyButton;
                @RightHeavyButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightHeavyButton;
                @RightHeavyButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightHeavyButton;
                @DPadUp.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadUp;
                @DPadUp.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadUp;
                @DPadUp.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadUp;
                @DPadDown.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadDown;
                @DPadDown.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadDown;
                @DPadDown.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadDown;
                @DPadLeft.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadLeft;
                @DPadRight.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadRight;
                @DPadRight.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadRight;
                @DPadRight.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnDPadRight;
            }
            m_Wrapper.m_PlayerGameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @CameraMovement.started += instance.OnCameraMovement;
                @CameraMovement.performed += instance.OnCameraMovement;
                @CameraMovement.canceled += instance.OnCameraMovement;
                @LockOn.started += instance.OnLockOn;
                @LockOn.performed += instance.OnLockOn;
                @LockOn.canceled += instance.OnLockOn;
                @EastButton.started += instance.OnEastButton;
                @EastButton.performed += instance.OnEastButton;
                @EastButton.canceled += instance.OnEastButton;
                @SouthButton.started += instance.OnSouthButton;
                @SouthButton.performed += instance.OnSouthButton;
                @SouthButton.canceled += instance.OnSouthButton;
                @NorthButton.started += instance.OnNorthButton;
                @NorthButton.performed += instance.OnNorthButton;
                @NorthButton.canceled += instance.OnNorthButton;
                @LeftLightButton.started += instance.OnLeftLightButton;
                @LeftLightButton.performed += instance.OnLeftLightButton;
                @LeftLightButton.canceled += instance.OnLeftLightButton;
                @LeftHeavyButton.started += instance.OnLeftHeavyButton;
                @LeftHeavyButton.performed += instance.OnLeftHeavyButton;
                @LeftHeavyButton.canceled += instance.OnLeftHeavyButton;
                @RightLightButton.started += instance.OnRightLightButton;
                @RightLightButton.performed += instance.OnRightLightButton;
                @RightLightButton.canceled += instance.OnRightLightButton;
                @RightHeavyButton.started += instance.OnRightHeavyButton;
                @RightHeavyButton.performed += instance.OnRightHeavyButton;
                @RightHeavyButton.canceled += instance.OnRightHeavyButton;
                @DPadUp.started += instance.OnDPadUp;
                @DPadUp.performed += instance.OnDPadUp;
                @DPadUp.canceled += instance.OnDPadUp;
                @DPadDown.started += instance.OnDPadDown;
                @DPadDown.performed += instance.OnDPadDown;
                @DPadDown.canceled += instance.OnDPadDown;
                @DPadLeft.started += instance.OnDPadLeft;
                @DPadLeft.performed += instance.OnDPadLeft;
                @DPadLeft.canceled += instance.OnDPadLeft;
                @DPadRight.started += instance.OnDPadRight;
                @DPadRight.performed += instance.OnDPadRight;
                @DPadRight.canceled += instance.OnDPadRight;
            }
        }
    }
    public PlayerGameplayActions @PlayerGameplay => new PlayerGameplayActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerGameplayActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCameraMovement(InputAction.CallbackContext context);
        void OnLockOn(InputAction.CallbackContext context);
        void OnEastButton(InputAction.CallbackContext context);
        void OnSouthButton(InputAction.CallbackContext context);
        void OnNorthButton(InputAction.CallbackContext context);
        void OnLeftLightButton(InputAction.CallbackContext context);
        void OnLeftHeavyButton(InputAction.CallbackContext context);
        void OnRightLightButton(InputAction.CallbackContext context);
        void OnRightHeavyButton(InputAction.CallbackContext context);
        void OnDPadUp(InputAction.CallbackContext context);
        void OnDPadDown(InputAction.CallbackContext context);
        void OnDPadLeft(InputAction.CallbackContext context);
        void OnDPadRight(InputAction.CallbackContext context);
    }
}
