//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player Gameplay"",
            ""id"": ""ffe028ad-f917-4048-b57c-edd31b8401fb"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8648a068-8fc3-4186-b7ae-8c7fa96fd415"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5049b5d6-dc12-4319-98e0-8ae5cc4ff627"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""641ae0d4-30ea-4823-a9d3-912e4ae35e2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""45739429-1aa6-47dd-9fd4-043f792211ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftLightButton"",
                    ""type"": ""Button"",
                    ""id"": ""9ba54142-917a-4979-ad0d-5337b71251f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHeavyButton"",
                    ""type"": ""Button"",
                    ""id"": ""760b26cf-2edc-4143-b19e-7feaa85c42ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightLightButton"",
                    ""type"": ""Button"",
                    ""id"": ""f4c30eb7-e7cc-43e1-8e37-072ac2e97a81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHeavyButton"",
                    ""type"": ""Button"",
                    ""id"": ""3414671a-3eab-49d2-84ba-b1ee8e739c08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlotChange"",
                    ""type"": ""Value"",
                    ""id"": ""edaa4c18-ba27-4fb7-9318-f9275b02f9d4"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""79ab54b0-685f-4083-8e3b-4859ff9cfc24"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""79de2aa7-f25f-41c5-9deb-e09b2109e53f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""edcb32ca-a572-4d19-b721-a337aca3ebf3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1ed87c68-4de2-4b46-b9da-44ec3b1bec0b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bf1b8193-b315-4490-9841-20cf0f0113a7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4235fa45-fc4f-42d2-8645-a95a8aa7c5d5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea7c2a78-14cd-43e8-940a-de05c251f997"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25e1dc45-2871-4118-98e0-023c0571adb3"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61a72952-e7f1-4b48-81f8-fa93eafdf0ad"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c8c9913-2193-4932-83fc-74c6165289c5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34da5b10-9bd1-4b6a-bbc0-71846cf828e8"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0874c3a4-732b-4e0c-93bf-d6f8ecbb9fc7"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a7ebb87-479e-4b69-aa63-51b0d7cf641b"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LeftLightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8b4befa-e368-4ee8-83bd-37900324fb8b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftLightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c699254-4271-4814-b6c7-1dd0d4e6851d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LeftHeavyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96e743ae-471e-47b4-913e-887248a7e66e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LeftHeavyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41a2948f-8d7a-4ccb-b63b-da14fe41cc9b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RightLightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""364367d2-cb7b-4b9f-9fda-5c1837411ee5"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightLightButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99ac181c-5051-4bc1-99f0-5798bb6dad95"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RightHeavyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02404cb6-7eb5-4832-af26-64564c749d5a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightHeavyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39acea42-7304-4dbf-8c03-5b87bd5861a3"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SlotChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""4cf7781e-ef8d-4bb2-abf7-aba8c93cdc08"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlotChange"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""020aa915-0910-463a-a752-776e899c9b36"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SlotChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d163389e-4084-45fe-b0cc-374188b58c53"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SlotChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""775a67af-bb08-4aa6-b4b4-5153e7a9df3d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SlotChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""dceae542-e4ed-47dc-b70d-4ebe8202d38e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SlotChange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player Gameplay
        m_PlayerGameplay = asset.FindActionMap("Player Gameplay", throwIfNotFound: true);
        m_PlayerGameplay_Movement = m_PlayerGameplay.FindAction("Movement", throwIfNotFound: true);
        m_PlayerGameplay_CameraMovement = m_PlayerGameplay.FindAction("CameraMovement", throwIfNotFound: true);
        m_PlayerGameplay_Roll = m_PlayerGameplay.FindAction("Roll", throwIfNotFound: true);
        m_PlayerGameplay_Sprint = m_PlayerGameplay.FindAction("Sprint", throwIfNotFound: true);
        m_PlayerGameplay_LeftLightButton = m_PlayerGameplay.FindAction("LeftLightButton", throwIfNotFound: true);
        m_PlayerGameplay_LeftHeavyButton = m_PlayerGameplay.FindAction("LeftHeavyButton", throwIfNotFound: true);
        m_PlayerGameplay_RightLightButton = m_PlayerGameplay.FindAction("RightLightButton", throwIfNotFound: true);
        m_PlayerGameplay_RightHeavyButton = m_PlayerGameplay.FindAction("RightHeavyButton", throwIfNotFound: true);
        m_PlayerGameplay_SlotChange = m_PlayerGameplay.FindAction("SlotChange", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player Gameplay
    private readonly InputActionMap m_PlayerGameplay;
    private IPlayerGameplayActions m_PlayerGameplayActionsCallbackInterface;
    private readonly InputAction m_PlayerGameplay_Movement;
    private readonly InputAction m_PlayerGameplay_CameraMovement;
    private readonly InputAction m_PlayerGameplay_Roll;
    private readonly InputAction m_PlayerGameplay_Sprint;
    private readonly InputAction m_PlayerGameplay_LeftLightButton;
    private readonly InputAction m_PlayerGameplay_LeftHeavyButton;
    private readonly InputAction m_PlayerGameplay_RightLightButton;
    private readonly InputAction m_PlayerGameplay_RightHeavyButton;
    private readonly InputAction m_PlayerGameplay_SlotChange;
    public struct PlayerGameplayActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerGameplayActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerGameplay_Movement;
        public InputAction @CameraMovement => m_Wrapper.m_PlayerGameplay_CameraMovement;
        public InputAction @Roll => m_Wrapper.m_PlayerGameplay_Roll;
        public InputAction @Sprint => m_Wrapper.m_PlayerGameplay_Sprint;
        public InputAction @LeftLightButton => m_Wrapper.m_PlayerGameplay_LeftLightButton;
        public InputAction @LeftHeavyButton => m_Wrapper.m_PlayerGameplay_LeftHeavyButton;
        public InputAction @RightLightButton => m_Wrapper.m_PlayerGameplay_RightLightButton;
        public InputAction @RightHeavyButton => m_Wrapper.m_PlayerGameplay_RightHeavyButton;
        public InputAction @SlotChange => m_Wrapper.m_PlayerGameplay_SlotChange;
        public InputActionMap Get() { return m_Wrapper.m_PlayerGameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerGameplayActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerGameplayActions instance)
        {
            if (m_Wrapper.m_PlayerGameplayActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnMovement;
                @CameraMovement.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnCameraMovement;
                @CameraMovement.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnCameraMovement;
                @CameraMovement.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnCameraMovement;
                @Roll.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRoll;
                @Roll.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRoll;
                @Roll.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRoll;
                @Sprint.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnSprint;
                @LeftLightButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftLightButton;
                @LeftLightButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftLightButton;
                @LeftLightButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftLightButton;
                @LeftHeavyButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftHeavyButton;
                @LeftHeavyButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftHeavyButton;
                @LeftHeavyButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnLeftHeavyButton;
                @RightLightButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightLightButton;
                @RightLightButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightLightButton;
                @RightLightButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightLightButton;
                @RightHeavyButton.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightHeavyButton;
                @RightHeavyButton.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightHeavyButton;
                @RightHeavyButton.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnRightHeavyButton;
                @SlotChange.started -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnSlotChange;
                @SlotChange.performed -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnSlotChange;
                @SlotChange.canceled -= m_Wrapper.m_PlayerGameplayActionsCallbackInterface.OnSlotChange;
            }
            m_Wrapper.m_PlayerGameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @CameraMovement.started += instance.OnCameraMovement;
                @CameraMovement.performed += instance.OnCameraMovement;
                @CameraMovement.canceled += instance.OnCameraMovement;
                @Roll.started += instance.OnRoll;
                @Roll.performed += instance.OnRoll;
                @Roll.canceled += instance.OnRoll;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @LeftLightButton.started += instance.OnLeftLightButton;
                @LeftLightButton.performed += instance.OnLeftLightButton;
                @LeftLightButton.canceled += instance.OnLeftLightButton;
                @LeftHeavyButton.started += instance.OnLeftHeavyButton;
                @LeftHeavyButton.performed += instance.OnLeftHeavyButton;
                @LeftHeavyButton.canceled += instance.OnLeftHeavyButton;
                @RightLightButton.started += instance.OnRightLightButton;
                @RightLightButton.performed += instance.OnRightLightButton;
                @RightLightButton.canceled += instance.OnRightLightButton;
                @RightHeavyButton.started += instance.OnRightHeavyButton;
                @RightHeavyButton.performed += instance.OnRightHeavyButton;
                @RightHeavyButton.canceled += instance.OnRightHeavyButton;
                @SlotChange.started += instance.OnSlotChange;
                @SlotChange.performed += instance.OnSlotChange;
                @SlotChange.canceled += instance.OnSlotChange;
            }
        }
    }
    public PlayerGameplayActions @PlayerGameplay => new PlayerGameplayActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerGameplayActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCameraMovement(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnLeftLightButton(InputAction.CallbackContext context);
        void OnLeftHeavyButton(InputAction.CallbackContext context);
        void OnRightLightButton(InputAction.CallbackContext context);
        void OnRightHeavyButton(InputAction.CallbackContext context);
        void OnSlotChange(InputAction.CallbackContext context);
    }
}
